### ISSUE TITLE
URL to Safe CLI needs updating

### ISSUE THREAD

**Issue by JPL1** [theWebalyst/vdash#2]
Get the SAFE CLI: either download using an install script or build the SAFE CLI locally. Instructions for both options are here.
-->
Get the Safe CLI: either download using an install script or build the SAFE CLI locally. Instructions for both options are here.
https://github.com/maidsafe/sn_api/tree/master/sn_cli

**Comment by theWebalyst** [comment]
Three links updated, thanks very much.
